name: learn-github-actions

run-name: ${{ github.actor }} is learning Github Actions

on: [push]

jobs:
  check-bats-version:
    runs-on: ubantu-latest
    stpes:
	- uses: actions/checkout@v4
	- uses: actions/setup-node@v4
	  with:
	    node-version: '20
	- run: npm install -g bats
	- run: bats -v
